### ISSUE TITLE
Shipping cost payment refund rejected from Stripe API because of negative charge value

### ISSUE THREAD

**Issue by rsmithlal** [solidusio/solidus_stripe#101]
Hi there,

I'm about to launch my first production store using Solidus and this solidus_stripe gem. While changing from a paid to a free shipping type after the order was placed, the automatic payment adjustment failed with a message that reads "This value must be greater than or equal to 1" for a charge of -$15. My Stripe account is currently in test mode, and I'm running the latest version of both Solidus and this gem.

Do you have any ideas for how I can resolve this issue? I would expect that the difference between the old price and new price would be applied and charged to the Stripe account on save.

**Comment by aldesantis** [comment]
@rsmithlal hey! 👋  Can you clarify what exactly is causing that error? Is it happening when you try to issue a refund via Stripe, or when you're trying to create an adjustment?

**Comment by rsmithlal** [comment]
Hi there, thanks for getting back to me =) It happens when I change the shipping type from one that has a higher price to one that has a lower price. My Solidus is set to auto capture payments, so it automatically sends a request to Stripe with the difference between the high and the low price when the order total changes. I haven't yet tested to make sure that it successfully charges Stripe when a more expensive shipping type is selected that increases the order total (instead of decreasing it). I thought that is was bit odd that there was no record in the adjustments table after this happened. I only found a new (failed) charge in the charges section of the UI. It's possible that this behaviour violates the expectations of the Stripe API. It seems like maybe charges have to be positive numbers (from the error message), so maybe we need to use a separate API endpoint to issue refunds like that when the value of the order total change is negative. Maybe the same as when a return refund is completed?  ---- On Sat, 30 Jan 2021 10:36:01 -0330  notifications@github.com  wrote ----

@rsmithlal hey! 👋  Can you clarify what exactly is causing that error? Is it happening when you try to issue a refund via Stripe, or when you're trying to create an adjustment?

**Comment by aldesantis** [comment]
@rsmithlal got it!

I think I'd need to know a bit more about your Solidus setup in order to help you figure out the issue: out of the box, Solidus will not create any payments automatically for an order when the total changes. The `auto_capture` option will simply capture _existing_ payments when the order is finalized (i.e., when it's initially completed from the storefront or the admin panel), but it will not attempt to create any payments or refunds after the order has been finalized.

This leads me to think you have some custom logic in your store that might be malfunctioning and causing the error you're seeing.

Since this doesn't seem related to solidus_stripe at the moment, would you mind jumping on the Solidus Slack (http://slack.solidus.io) so that we can continue the discussion there? Thanks!
