### ISSUE TITLE
Consistency between README and Wiki

### ISSUE THREAD

**Issue by brchristian** [solidusio/solidus_stripe#67]
When I look at the current [README](https://github.com/solidusio/solidus_stripe/blob/master/README.md), I see `'stripe_env_credentials'`, but when I look at the [wiki](https://github.com/solidusio/solidus_stripe/wiki/Migrating-from-solidus_gateway), I see `'stripe_credentials',`. Is one of these incorrect?

**Comment by kennyadsl** [comment]
Thanks for opening this issue. They are both correct, it's just the name of the group of preferences that you'll see in the admin panel in the Stripe payment method form. In the wiki it's not using ENV variables while in the README it does, that's why they are different. I agree with should make them uniform though. The `_env_` part is not strictly required.

**Comment by chrean** [comment]
Looks like @kennyadsl answered the question, closing. Please feel free to create a new issue if necessary.
